### PR TITLE
Small fixes to themes

### PR DESCRIPTION
**Pull request by asinghvi17**

### CODE REVIEW

**Comment by asinghvi17** [comment]
@mkborregaard there is a weird OpenGL bug which Simon is investigating, may be related to why MakieThemes fails.  When do you often see failures?

**Comment by mkborregaard** [comment]
whenever I use it

**Comment by asinghvi17** [comment]
Could you post errors/stacktraces/things that look wrong in an issue?  Would be easier for us to fix it then.

**Comment by mkborregaard** [comment]
It's just that the themes aren't applied at all.
Try the readme example :-)

**Pull request merged**
