### PR TITLE
[WIP] Add 3d support to ggthemr

### PR DESCRIPTION
**Pull request by asinghvi17**
Seems like this should be rather simple...

Edit: It seems it will not be quite as simple as envisioned.

TODOs:
- [ ] Figure out how to transmit linestyle into the frame or grid of Axis3d
- [ ] Make it look generally less ugly

### CODE REVIEW

**Comment by mkborregaard** [comment]
nice! could you post an example?

**Comment by asinghvi17** [comment]
Will do, just testing at the moment. 
 It's kind of interesting, but the 3d linestyle and framestyle don't appear to be themable in the way that the 2d ones are...

**Comment by asinghvi17** [comment]
```julia
using Makie, MakieThemes

AbstractPlotting.set_theme!(ggthemr(:fresh))

meshscatter(rand(10), rand(10), rand(10))
```

3d-fig1

**Comment by asinghvi17** [comment]
Colors looking good:

```julia
using Makie, MakieThemes

AbstractPlotting.set_theme!(ggthemr(:chalk))

meshscatter(rand(10), rand(10), rand(10), color = rand(10))
```
3d-fig2

**Comment by mkborregaard** [comment]
Yes the colors look nice. It's just the axes but I feel like the look of the  3d-axes isn't yet finished in Makie.

**Comment by asinghvi17** [comment]
Billboarding would be really nice if we can get it, for the axis labels

(also these plots are really low resolution so that probably explains some of the ugliness)

**Comment by asinghvi17** [comment]
Pinging @SimonDanisch, is there any way to modify grid attributes of Axis3d or will we need to attempt to add that as a feature in AbstractPlotting?

**Comment by asinghvi17** [comment]
Per conversation over at JuliaPlots/AbstractPlotting.jl#115, it seems that `linestyle` will not be able to be transmitted without a rework of `Axis3D`'s mechanism for generating Frames.  Currently, the Frames are drawn as one `linebuffer`, so their linestyle can't be changed _individually_.  

To be able to change the linestyle we can probably add a `linestyle` attribute to `Axis3d` whose type is `Union{Nothing, Symbol}`.  That would globally change the linestyle for all of the grids (and the frames if not individually set) - it's a bit of a hack, but might work.

**Comment by asinghvi17** [comment]
Here's the main issue - for full themability, we'll need to be able to customize how `Axis3D` is drawn.  Is there any way to do that aside from overriding the method itself?

**Comment by mkborregaard** [comment]
Is this still wip?

**Comment by SimonDanisch** [comment]
We could just merge this and improve it later?

**Comment by asinghvi17** [comment]
Yeah, nothing else I can do here without changes in AbstractPlotting I think.

**Comment by mkborregaard** [comment]
orsom

**Pull request merged**
